### PR TITLE
docs: add new blog post

### PR DESCRIPTION
**Pull request by Kira272921**
## Fixes Issue

- #94 

## Changes proposed

Add new blog post on "How to build a blog using Remix and MDX"

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by gouravkhunger** [comment]
Hey, we changed the repo name from `genicsblog.github.io` to `genicsblog.com`. Can you do it for your fork so that the checks pass? Thank you 😄

**Comment by Kira272921** [comment]
> Hey, we changed the repo name from `genicsblog.github.io` to `genicsblog.com`. Can you do it for your fork so that the checks pass? Thank you 😄

Ohhh... I didn't notice it 👀, will do it right now :D

**Comment by Kira272921** [comment]
I have changed my fork's name to `genicsblog.com`

**Comment by gouravkhunger** [comment]
Thanks!

**Pull request merged**
